# Schedule

This is a tentative schedule, **BUT** I will do my very best to stick to it, so that you may plan accordingly!

## Spring 2023  {-}				
				
Date | Topic | 				
|:-------|:------				
| 	Monday, January 9, 2023	| 	First Day Fun!	| 
| 	Wednesday, January 11, 2023	| 	R basics and install	| 
| 	Friday, January 13, 2023	| 	**About Me Due** and R basics and workflows	| 
| 	Monday, January 16, 2023	| 	Martin Luther King, Jr. Holiday	| 
| 	Wednesday, January 18, 2023	| 	Objects and Arithmetic	| 
| 	Friday, January 20, 2023	| 	**QUIZ: R Basics** 	| 
| 	Monday, January 23, 2023	| 	Summaries and Subscripting	| 
| 	Wednesday, January 25, 2023	| 	Case: GDH Ice Cream	| 
| 	Friday, January 27, 2023	| 	**QUIZ: dataframes**	| 
| 	Monday, January 30, 2023	| 	Matrices and `mtcars`	|
| 	Wednesday, February 1, 2023	| 	Real Data & Summary Statistics	| 
| 	Friday, February 3, 2023	| 	**QUIZ: Real Data & Statistics**	| 
| 	Monday, February 6, 2023	| 	Review	| 
| 	Wednesday, February 8, 2023	| 	**EXAM 1**	| 
| 	Friday, February 10, 2023	| 	Linear Regression	| 
| 	Monday, February 13, 2023	| 	Multivariate Regression	| 
| 	Wednesday, February 15, 2023	| 	**QUIZ: Linear Reg**	| 
| 	Friday, February 17, 2023	| Social Dilemma & SEDSI		| 
| 	Monday, February 20, 2023	| 	Social Dilemma and dplyr	| 
| 	Wednesday, February 22, 2023	| 	dplyr: filter and select	| 
| 	Friday, February 24, 2023	| 	**QUIZ: BASIC dplyr**	| 
| 	Monday, February 27, 2023	|	dplyr: group_by, summarise, tally, mutate	| 
| 	Wednesday, March 1, 2023	| Real data	 	| 
| 	Friday, March 3, 2023	| **QUIZ: more, better dplyr**	 	| 
| 	Monday, March 6, 2023	| 	Review	| 
| 	Wednesday, March 8, 2023	| 	**EXAM 2**	| 
| 	Friday, March 10, 2023	| 	Strategic Plan Launch (No classes)	| 
|	Monday, March 13, 2023	| 	SPRING BREAK	| 
| 	Wednesday, March 15, 2023	| 	SPRING BREAK	| 
|	Friday, March 17, 2023	| 	SPRING BREAK	| 
|	Monday, March 20, 2023	| 	NFL	| 
|	Wednesday, March 22, 2023	| 	NFL	| 
|	Friday, March 24, 2023	| 	**QUIZ: NFL**	| 
|	Monday, March 27, 2023	| 	ggplot2	| 
|	Wednesday, March 29, 2023	| 	ggplot2	| 
|	Friday, March 31, 2023	| 	**QUIZ: ggplot2**	| 
|	Monday, April 3, 2023	| 	Advising Week	| 
|	Wednesday, April 5, 2023	| 	Advising Week	| 
|	Friday, April 7, 2023	| 	Easter Holidays	| 
|	Monday, April 10, 2023	| 	Easter Holidays	| 
|	Wednesday, April 12, 2023	| 	Registration Week	| 
|	Friday, April 14, 2023	| **EXAM 3**		| 
|	Monday, April 17, 2023	| 	Rmarkdown	| 
|	Wednesday, April 19, 2023	| 	Rmarkdown	| 
|	Friday, April 21, 2023	| 	**QUIZ: ggplot2**	| 
|	Monday, April 24, 2023	| 	Review	| 
|	Wednesday, April 26, 2023	| 	Review	| 
|	Friday, April 28, 2023	| 	**LAST DAY OF CLASSES**	| 
|	Wednesday, May 3, 2023	| 	**FINAL 1:30 p.m. – E period **	| 

